trigger:
  branches:
    include:
    - master

jobs:

- job: 'Test'
  displayName: "Evaluate cookiecutter template"

  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-16.04'
      macOS:
        imageName: 'macos-10.13'
      Windows:
        imageName: 'vs2017-win2016'

  pool:
    vmImage: $(imageName)

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools
      python -m pip install cookiecutter
    displayName: 'Install build dependencies'

  - bash: |
      python -m cookiecutter --no-input --output-dir "$(Agent.BuildDirectory)" "$(Build.SourcesDirectory)"
    displayName: 'Evaluate template'


